/**
* Annotated FlashAttention dylib generated by the 𝚒 C backend.
*
* This code is exactly as emitted by 𝚒's C backend except for comments and
* whitespace.
*/
#include <math.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct { const float* data; const size_t* shape; const size_t rank; } Tensor;
typedef struct { float* data; const size_t* shape; const size_t rank; } TensorMut;
typedef struct { const float* data; const size_t* shape; const size_t* layout; } View;
typedef struct { float* data; const size_t* shape; const size_t* layout; } ViewMut;

static inline ViewMut alloc_view_mut(size_t ndims, const size_t* layout, const size_t* shape) {
  size_t n = 1;
  for (size_t i = 0; i < ndims; ++i) n *= layout[i];
  float* data = (float*)malloc(n * sizeof(float));
  return (ViewMut){ .data = data, .shape = shape, .layout = layout };
}

static inline View as_view(const Tensor* t) {
  return (View){ .data = t->data, .shape = t->shape, .layout = t->shape };
}

static inline ViewMut as_view_mut(const TensorMut* t) {
  return (ViewMut){ .data = t->data, .shape = t->shape, .layout = t->shape };
}

static inline View view_mut_as_view(const ViewMut* t) {
  return (View){ .data = t->data, .shape = t->shape, .layout = t->layout };
}

size_t count(void) {
  return 1;
}

void ranks(size_t* ranks) {
  ranks[0] = 2;
  return;
}

void shapes(const Tensor* inputs, size_t** shapes) {
  shapes[0][0] = inputs[0].shape[0];
  shapes[0][1] = inputs[2].shape[1];
  return;
}

// FlashAttention
void f0(const View* readonlys, ViewMut* writeables) {
  for (size_t i0 = 0; i0 < (writeables[9].shape[2] + 16 - 1) / 16; ++i0) {
    for (size_t i1 = 0; i1 < (writeables[9].shape[0] + 16 - 1) / 16; ++i1) {

      // compute tile S_ij = Q_i @ K_j
      for (size_t i11 = 0; i11 < 16; ++i11) {
        if (i1 * 16 + i11 < writeables[0].shape[0]) {
          for (size_t i12 = 0; i12 < 16; ++i12) {
            if (i0 * 16 + i12 < writeables[0].shape[1]) {
              // init S_ij (per element)
              writeables[1].data[
                i11 * writeables[1].layout[1] +
                i12
              ] = 0.0f;

              for (size_t i13 = 0; i13 < writeables[0].shape[2]; ++i13) {
                // S_ij accumulator
                writeables[0].data[0] = readonlys[0].data[
                  (i1 * 16 + i11) * readonlys[0].layout[1] +
                  i13
                ] * readonlys[1].data[
                  (i0 * 16 + i12) * readonlys[1].layout[1] +
                  i13
                ];

                // accumulate into S_ij
                writeables[1].data[
                  i11 * writeables[1].layout[1] +
                  i12
                ] = writeables[1].data[
                  i11 * writeables[1].layout[1] +
                  i12
                ] + writeables[0].data[0];
              }
            }
          }
        }
      }

      // compute tile max and running max
      for (size_t i14 = 0; i14 < 16; ++i14) {
        if (i1 * 16 + i14 < writeables[1].shape[0]) {
          if (i0 == 0) {
            // init max m_i
            writeables[3].data[
              i1 * 16 +
              i14
            ] = (-INFINITY);
          }

          // store running max m_i'
          writeables[2].data[
            i1 * 16 +
            i14
          ] = writeables[3].data[
            i1 * 16 +
            i14
          ];

          // compute tile max m_i
          for (size_t i15 = 0; i15 < 16; ++i15) {
            if (i0 * 16 + i15 < writeables[1].shape[1]) {
              writeables[3].data[
                i1 * 16 +
                i14
              ] = fmaxf(writeables[3].data[
                i1 * 16 +
                i14
              ], writeables[1].data[
                i14 * writeables[1].layout[1] +
                i15
              ]);
            }
          }
        }
      }

      // max shift tile
      for (size_t i9 = 0; i9 < 16; ++i9) {
        if (i1 * 16 + i9 < writeables[1].shape[0]) {
          for (size_t i10 = 0; i10 < 16; ++i10) {
            if (i0 * 16 + i10 < writeables[1].shape[1]) {
              writeables[4].data[
                i9 * writeables[4].layout[1] +
                i10
              ] = writeables[1].data[
                i9 * writeables[1].layout[1] +
                i10
              ] - writeables[3].data[
                i1 * 16 +
                i9
              ];
            }
          }
        }
      }

      // compute P_ij = exp(S_ij - m_ij)
      for (size_t i7 = 0; i7 < 16; ++i7) {
        if (i1 * 16 + i7 < writeables[4].shape[0]) {
          for (size_t i8 = 0; i8 < 16; ++i8) {
            if (i0 * 16 + i8 < writeables[4].shape[1]) {
              writeables[5].data[
                i7 * writeables[5].layout[1] +
                i8
              ] = powf(2.71828175f, writeables[4].data[
                i7 * writeables[4].layout[1] +
                i8
              ]);
            }
          }
        }
      }

      // compute tile sum and running sum
      for (size_t i19 = 0; i19 < 16; ++i19) {
        if (i1 * 16 + i19 < writeables[5].shape[0]) {
          if (i0 == 0) {
            // init sum l_i
            writeables[7].data[
              i1 * 16 +
              i19
            ] = 0.0f;
          }

          // store running sum l_i'
          writeables[6].data[
            i1 * 16 +
            i19
          ] = writeables[7].data[
            i1 * 16 +
            i19
          ];

          // scale l_i' by correction factor exp(m_i' - m_i)
          writeables[7].data[
            i1 * 16 +
            i19
          ] = writeables[7].data[
            i1 * 16 +
            i19
          ] * powf(2.71828175f, writeables[2].data[
            i1 * 16 +
            i19
          ] - writeables[3].data[
            i1 * 16 +
            i19
          ]);

          // compute tile sum l_i
          for (size_t i20 = 0; i20 < 16; ++i20) {
            if (i0 * 16 + i20 < writeables[5].shape[1]) {
              writeables[7].data[
                i1 * 16 +
                i19
              ] = writeables[7].data[
                i1 * 16 +
                i19
              ] + writeables[5].data[
                i19 * writeables[5].layout[1] +
                i20
              ];
            }
          }
        }
      }

      // normalize tile
      for (size_t i5 = 0; i5 < 16; ++i5) {
        if (i1 * 16 + i5 < writeables[5].shape[0]) {
          for (size_t i6 = 0; i6 < 16; ++i6) {
            if (i0 * 16 + i6 < writeables[5].shape[1]) {
              writeables[8].data[
                i5 * writeables[8].layout[1] +
                i6
              ] = writeables[5].data[
                i5 * writeables[5].layout[1] +
                i6
              ] / writeables[7].data[
                i1 * 16 +
                i5
              ];
            }
          }
        }
      }

      // compute O_i = corrected O_i + (P_ij @ V_j)
      for (size_t i2 = 0; i2 < 16; ++i2) {
        if (i1 * 16 + i2 < writeables[9].shape[0]) {

          // scale O_i by correction factor exp(m_i' - m_i)
          for (size_t i23 = 0; i23 < writeables[9].shape[1]; ++i23) {
            writeables[10].data[
              (i1 * 16 + i2) * writeables[10].layout[1] +
              i23
            ] = writeables[10].data[
              (i1 * 16 + i2) * writeables[10].layout[1] +
              i23
            ] * powf(2.71828175f, writeables[2].data[
              i1 * 16 +
              i2
            ] - writeables[3].data[
              i1 * 16 +
              i2
            ]);
          }

          // scale O_i by correction factor (l_i' - l_i)
          for (size_t i24 = 0; i24 < writeables[9].shape[1]; ++i24) {
            writeables[10].data[
              (i1 * 16 + i2) * writeables[10].layout[1] +
              i24
            ] = writeables[10].data[
              (i1 * 16 + i2) * writeables[10].layout[1] +
              i24
            ] * (writeables[6].data[
              i1 * 16 +
              i2
            ] / writeables[7].data[
              i1 * 16 +
              i2
            ]);
          }

          for (size_t i3 = 0; i3 < writeables[9].shape[1]; ++i3) {
            if (i0 == 0) {
              // init O_ij (per element)
              writeables[10].data[
                (i1 * 16 + i2) * writeables[10].layout[1] +
                i3
              ] = 0.0f;
            }
            for (size_t i4 = 0; i4 < 16; ++i4) {
              if (i0 * 16 + i4 < writeables[9].shape[2]) {
                // O_ij accumulator
                writeables[9].data[0] = writeables[8].data[
                  i2 * writeables[8].layout[1] +
                  i4
                ] * readonlys[2].data[
                  (i0 * 16 + i4) * readonlys[2].layout[1] +
                  i3
                ];
                // accumulate into O_ij
                writeables[10].data[
                  (i1 * 16 + i2) * writeables[10].layout[1] +
                  i3
                ] = writeables[10].data[
                  (i1 * 16 + i2) * writeables[10].layout[1] +
                  i3
                ] + writeables[9].data[0];
              }
            }
          }
        }
      }
    }
  }
}

void exec(const Tensor* inputs, TensorMut* outputs) {
  const View in0 = as_view(&inputs[0]);
  const View in1 = as_view(&inputs[1]);
  const View in2 = as_view(&inputs[2]);
  ViewMut out0 = as_view_mut(&outputs[0]);

  // S_ij accumulator
  const size_t* s0_layout = NULL; // scalar alloc
  const size_t s0_shape[] = {
    inputs[0].shape[0],
    inputs[1].shape[0],
    inputs[0].shape[1]
  };
  ViewMut s0 = alloc_view_mut(0, NULL, s0_shape);

  // S_ij
  const size_t s1_layout[] = { 16, 16 }; // tile alloc
  const size_t s1_shape[] = {
    inputs[0].shape[0],
    inputs[1].shape[0]
  };
  ViewMut s1 = alloc_view_mut(2, s1_layout, s1_shape);

  // tile max m_i
  const size_t s2_layout[] = { inputs[0].shape[0] }; // [N] alloc
  const size_t s2_shape[] = { inputs[0].shape[0] };
  ViewMut s2 = alloc_view_mut(1, s2_layout, s2_shape);

  // max-shifted S_ij
  const size_t s3_layout[] = { 16, 16 }; // tile alloc
  const size_t s3_shape[] = {
    inputs[0].shape[0],
    inputs[1].shape[0]
  };
  ViewMut s3 = alloc_view_mut(2, s3_layout, s3_shape);

  // P_ij
  const size_t s4_layout[] = { 16, 16 }; // tile alloc
  const size_t s4_shape[] = {
    inputs[0].shape[0],
    inputs[1].shape[0]
  };
  ViewMut s4 = alloc_view_mut(2, s4_layout, s4_shape);

  // tile sum l_i
  const size_t s5_layout[] = { inputs[0].shape[0] }; // [N] alloc
  const size_t s5_shape[] = { inputs[0].shape[0] };
  ViewMut s5 = alloc_view_mut(1, s5_layout, s5_shape);

  // normalized P_ij
  const size_t s6_layout[] = { 16, 16 }; // tile alloc
  const size_t s6_shape[] = {
    inputs[0].shape[0],
    inputs[1].shape[0]
  };
  ViewMut s6 = alloc_view_mut(2, s6_layout, s6_shape);

  // O_i acc
  const size_t* s7_layout = NULL; // scalar alloc
  const size_t s7_shape[] = {
    inputs[0].shape[0],
    inputs[2].shape[1],
    inputs[1].shape[0]
  };
  ViewMut s7 = alloc_view_mut(0, NULL, s7_shape);

  // running max m_i'
  const size_t s8_layout[] = { inputs[0].shape[0] }; // [N] alloc
  const size_t s8_shape[] = { inputs[0].shape[0] };
  ViewMut s8 = alloc_view_mut(1, s8_layout, s8_shape);

  // running sum l_i'
  const size_t s9_layout[] = { inputs[0].shape[0] }; // [N] alloc
  const size_t s9_shape[] = { inputs[0].shape[0] };
  ViewMut s9 = alloc_view_mut(1, s9_layout, s9_shape);

  // single kernel dispatch
  f0(
    (const View[]){
      in0,
      in1,
      in2
    },
    (ViewMut[]){
      s0,  // S_ij acc
      s1,  // S_ij
      s8,  // running max m_i'
      s2,  // tile max m_i
      s3,  // max-shifted S_ij
      s4,  // P_ij
      s9,  // running sum l_i'
      s5,  // tile sum l_i
      s6,  // normalized P_ij
      s7,  // O_i acc
      out0 // O_i
    }
  );

  free(s9.data);
  free(s8.data);
  free(s7.data);
  free(s6.data);
  free(s5.data);
  free(s4.data);
  free(s3.data);
  free(s2.data);
  free(s1.data);
  free(s0.data);

  return;
}
